using ScaleFXStudio.Models;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

namespace ScaleFXStudio.Services;

public class ConfigService
{
    private readonly IDeserializer _deserializer;
    private readonly ISerializer _serializer;

    public ConfigService()
    {
        _deserializer = new DeserializerBuilder()
            .WithNamingConvention(UnderscoredNamingConvention.Instance)
            .IgnoreUnmatchedProperties()
            .Build();

        _serializer = new SerializerBuilder()
            .WithNamingConvention(UnderscoredNamingConvention.Instance)
            .ConfigureDefaultValuesHandling(DefaultValuesHandling.OmitNull)
            .Build();
    }

    public ScaleFXConfiguration Load(string filePath)
    {
        var yaml = File.ReadAllText(filePath);
        return _deserializer.Deserialize<ScaleFXConfiguration>(yaml) ?? new ScaleFXConfiguration();
    }

    public void Save(string filePath, ScaleFXConfiguration config)
    {
        var yaml = _serializer.Serialize(config);
        
        // Add header comment
        var header = """
            # ScaleFX Hub Configuration File
            # Generated by ScaleFX Studio Editor
            # See docs/README.md for configuration details
            
            """;
        
        File.WriteAllText(filePath, header + yaml);
    }

    public ScaleFXConfiguration CreateDefault()
    {
        return new ScaleFXConfiguration
        {
            EngineFx = new EngineFxConfig
            {
                Enabled = true,
                EngineToggle = new PwmInputConfig { Pin = 17, ThresholdUs = 1500 },
                Sounds = new EngineSoundsConfig
                {
                    Starting = new SoundFileConfig { File = "~/assets/engine_start.wav" },
                    Running = new SoundFileConfig { File = "~/assets/engine_loop.wav" },
                    Stopping = new SoundFileConfig { File = "~/assets/engine_stop.wav" },
                    Transitions = new TransitionsConfig
                    {
                        StartingOffsetMs = 60000,
                        StoppingOffsetMs = 25000
                    }
                }
            },
            GunFx = new GunFxConfig
            {
                Enabled = true,
                Trigger = new TriggerConfig { Pin = 27 },
                Smoke = new SmokeConfig
                {
                    Enabled = true,
                    HeaterTogglePin = 22,
                    HeaterPwmThresholdUs = 1500
                },
                TurretControl = new TurretControlConfig
                {
                    Pitch = new ServoConfig
                    {
                        Enabled = true,
                        ServoId = 1,
                        PwmPin = 13,
                        InputMinUs = 1000,
                        InputMaxUs = 2000,
                        OutputMinUs = 1000,
                        OutputMaxUs = 2000,
                        MaxSpeedUsPerSec = 500.0,
                        MaxAccelUsPerSec2 = 2000.0,
                        UpdateRateHz = 50
                    },
                    Yaw = new ServoConfig
                    {
                        Enabled = true,
                        ServoId = 2,
                        PwmPin = 16,
                        InputMinUs = 1000,
                        InputMaxUs = 2000,
                        OutputMinUs = 1000,
                        OutputMaxUs = 2000,
                        MaxSpeedUsPerSec = 500.0,
                        MaxAccelUsPerSec2 = 2000.0,
                        UpdateRateHz = 50
                    }
                },
                RateOfFire = new List<RateOfFireConfig>
                {
                    new() { Name = "200", Rpm = 200, PwmThresholdUs = 1400, Sound = "~/assets/gun_200rpm.wav" },
                    new() { Name = "550", Rpm = 550, PwmThresholdUs = 1600, Sound = "~/assets/gun_550rpm.wav" }
                }
            }
        };
    }
}
